version: "3.9"
services:
  pg:
    image: postgres
    restart: always
    ports: 
      - 5432:5432    
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_PASSWORD: 1q2w3e!
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8091:80
    environment:
      PGADMIN_DEFAULT_EMAIL: student@hu.nl
      PGADMIN_DEFAULT_PASSWORD: 1q2w3e!